version: '3.8'
services:
  postgres:
    container_name: Postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev123
      - POSTGRES_DB=eksamen
    ports:
      - 5432:5432
    networks:
      - banking

  python3:
    build: .
    container_name: Python3
    environment:
      # POSTGRES
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev123
      - POSTGRES_DB=eksamen
    depends_on:
      - postgres
    ports:
      - 5000:5000
    networks:
      - banking
      
networks:
  banking: 
