version: '3.8'
services:
  postgres:
    container_name: Postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev123
      - POSTGRES_DB=eksamen
    ports:
      - 5432:5432
    networks:
      - banking

  # bankingimage:
  #   image: ghcr.io/lassebirk96/bankingcomponent:latest
  #   container_name: bankingimage
  #   environment:
  #     # POSTGRES
  #     - POSTGRES_HOST=postgres
  #     - POSTGRES_PORT=5432
  #     - POSTGRES_USER=dev
  #     - POSTGRES_PASSWORD=dev123
  #     - POSTGRES_DB=eksamen
  #   depends_on:
  #     - postgres
  #   ports:
  #     - 5000:5000
  #   networks:
  #     - banking

  banking:
    build: 
      context: .
      args:
        - COMPONENT_PATH=BankingComponent
    container_name: banking
    environment:
      # POSTGRES
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev123
      - POSTGRES_DB=eksamen
    depends_on:
      - postgres
    ports:
      - 5000:5000
    networks:
      - banking
      
networks:
  banking: 
