version: '3.8'
services:

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev123
      - POSTGRES_DB=Exam22
    ports:
      - '5432:5432'

  python3:
    build: .
    container_name: python3
    environment:
      # POSTGRES
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev123
      - POSTGRES_DB=Exam22
     
    depends_on:
      - postgres
    ports:
      - 5000:5000