name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt install python3 python3-pip python3-pytest
          sudo apt install python3 python3-pip python3-pytest-postgresql
          
      - name: Run tests
        run: sudo pytest-3
        
      - name: Run build script
        run: ./build.sh