name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt install python3 python3-pip python3-pytest
          sudo apt-get install python3-flask-bcrypt
          sudo apt-get install python3-pip
          sudo apt install python3-dev libpq-dev
          sudo apt install postgresql
          sudo pip3 install psycopg2-binary
          sudo pip3 install psycopg
          sudo pip3 install pytest-postgresql
          sudo systemctl start postgresql.service
          export LANG="en_US.UTF-8" 
          export LC_ALL="en_US.UTF-8"
          export LC_CTYPE="en_US.UTF-8"
          pg_createcluster postgresql
          

      - name: Run tests
        run: sudo pytest-3
        
      - name: Run build script
        run: ./build.sh